server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bms_payment_db
    username: bms_user
    password: bms_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

# Stripe Configuration
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY:pk_test_your_stripe_publishable_key}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret_key}

# Logging
logging:
  level:
    com.bms.payment: DEBUG
    com.stripe: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
